# Generated by Django 2.0 on 2018-07-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_project_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
