# Generated by Django 2.0 on 2018-07-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.URLField(),
        ),
    ]
