# Generated by Django 2.0 on 2018-07-24 15:01

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180724_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(upload_to=pages.models.get_upload_file_name),
        ),
    ]
