# Generated by Django 2.0 on 2018-07-25 08:47

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
